import fs from 'fs';
import path from 'path';

/**
 * Local Farcaster user store reader.
 * Source of truth: data/farcaster_map.json (generated by scripts/users-index.mjs)
 */

export type FarcasterUserLite = {
  fid: number;
  username: string | null;
  display_name: string | null;
  pfp_url: string | null;
};

export type FarcasterUserProfile = FarcasterUserLite & {
  bio_text: string | null;
  follower_count: number | null;
  following_count: number | null;
  /** Prefer `score` when present. */
  score: number | null;
  /** Legacy field stored under `experimental.neynar_user_score`. */
  neynar_user_score: number | null;
};

type FarcasterMapOk = {
  status: 'ok';
  fid?: unknown;
  username?: unknown;
  display_name?: unknown;
  pfp_url?: unknown;
  profile?: unknown;
  follower_count?: unknown;
  following_count?: unknown;
  score?: unknown;
  experimental?: unknown;
};

type FarcasterMapNotFound = { status: 'not_found' };
type FarcasterMapError = { status: 'error' };

type FarcasterMapEntry = (FarcasterMapOk | FarcasterMapNotFound | FarcasterMapError) & {
  updated_at_utc?: string;
  [k: string]: unknown;
};

type FarcasterMapFile = Record<string, unknown>;

function isEthAddress(s: string): boolean {
  return /^0x[a-fA-F0-9]{40}$/.test(s);
}

export function normalizeAddressLower(address: string): string | null {
  const a = address.trim();
  if (!isEthAddress(a)) return null;
  return a.toLowerCase();
}

function readJsonFileSafe(filePath: string): unknown {
  try {
    if (!fs.existsSync(filePath)) return {};
    const raw = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(raw) as unknown;
  } catch {
    return {};
  }
}

export function readFarcasterMap(): FarcasterMapFile {
  const p = path.join(process.cwd(), 'data', 'farcaster_map.json');
  const obj = readJsonFileSafe(p);
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) return {};
  return obj as FarcasterMapFile;
}

function asEntry(v: unknown): FarcasterMapEntry | null {
  if (typeof v !== 'object' || v === null || Array.isArray(v)) return null;
  const e = v as FarcasterMapEntry;
  if (typeof e.status !== 'string') return null;
  return e;
}

function asStringOrNull(v: unknown): string | null {
  return typeof v === 'string' ? v : null;
}

function asNumberOrNull(v: unknown): number | null {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string') {
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function extractBioText(profile: unknown): string | null {
  if (typeof profile !== 'object' || profile === null || Array.isArray(profile)) return null;
  const p = profile as Record<string, unknown>;
  const bio = p.bio;
  if (typeof bio !== 'object' || bio === null || Array.isArray(bio)) return null;
  const b = bio as Record<string, unknown>;
  return asStringOrNull(b.text);
}

function extractNeynarUserScore(experimental: unknown): number | null {
  if (typeof experimental !== 'object' || experimental === null || Array.isArray(experimental)) return null;
  const ex = experimental as Record<string, unknown>;
  return asNumberOrNull(ex.neynar_user_score);
}

function toLite(entry: FarcasterMapEntry): FarcasterUserLite | null {
  if (entry.status !== 'ok') return null;

  const fid = asNumberOrNull(entry.fid);
  if (fid == null) return null;

  const username = asStringOrNull(entry.username);
  const display_name = asStringOrNull(entry.display_name);
  const pfp_url = asStringOrNull(entry.pfp_url);

  return { fid, username, display_name, pfp_url };
}

function toProfile(entry: FarcasterMapEntry): FarcasterUserProfile | null {
  const lite = toLite(entry);
  if (!lite) return null;

  const bio_text = extractBioText((entry as FarcasterMapOk).profile);
  const follower_count = asNumberOrNull((entry as FarcasterMapOk).follower_count);
  const following_count = asNumberOrNull((entry as FarcasterMapOk).following_count);

  const score = asNumberOrNull((entry as FarcasterMapOk).score);
  const neynar_user_score = extractNeynarUserScore((entry as FarcasterMapOk).experimental);

  return {
    ...lite,
    bio_text,
    follower_count,
    following_count,
    score,
    neynar_user_score,
  };
}

export function lookupFarcasterUserByAddress(address: string): FarcasterUserLite | null {
  const key = normalizeAddressLower(address);
  if (!key) return null;

  const map = readFarcasterMap();
  const entry = asEntry(map[key]);
  if (!entry) return null;
  return toLite(entry);
}

export function lookupFarcasterProfileByAddress(address: string): FarcasterUserProfile | null {
  const key = normalizeAddressLower(address);
  if (!key) return null;

  const map = readFarcasterMap();
  const entry = asEntry(map[key]);
  if (!entry) return null;
  return toProfile(entry);
}

export function lookupFarcasterUsersByAddresses(addresses: string[]): Record<string, FarcasterUserLite | null> {
  const map = readFarcasterMap();
  const out: Record<string, FarcasterUserLite | null> = {};

  for (const a of addresses) {
    const key = normalizeAddressLower(a);
    if (!key) continue;

    const entry = asEntry(map[key]);
    out[key] = entry ? toLite(entry) : null;
  }

  return out;
}
